#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Oct 21 10:26:18 CEST 2021
maven-metadata-maven-evoting-virtual.xml.lastUpdated=1634804778910
